Modal
dmitrykorochkin/Dev_project pull request #3
Opened 2022-12-01 19:04 UTC by dmitrykorochkin

add typescript code

2022-12-01 19:18 UTC, andrey-kudinov requested changes
Старайся по максимуму избегать any

2022-12-01 20:05 UTC, andrey-kudinov commented on src/ts/modules/modals.ts
> +      trigger.addEventListener("click", (e: any) => {
type Event probably

2022-12-01 20:05 UTC, andrey-kudinov commented on src/ts/modules/modals.ts
> +    const closeModal:any = () => {
I guess it could be `Function`

2022-12-02 15:35 UTC, dmitrykorochkin commented on src/ts/modules/modals.ts
> +      trigger.addEventListener("click", (e: any) => {
✅

2022-12-02 15:35 UTC, dmitrykorochkin commented on src/ts/modules/modals.ts
> +    const closeModal:any = () => {
✅

2022-12-02 16:34 UTC, merged