Tabs
dmitrykorochkin/Dev_project pull request #5
Opened 2022-12-04 11:19 UTC by dmitrykorochkin

Added tab switching functionality

2022-12-04 14:25 UTC, andrey-kudinov requested changes

2022-12-04 14:25 UTC, andrey-kudinov commented on src/ts/main.ts
> +    tabs('.decoration_slider', '.no_click', '.decoration_content > div > div', 'after_click');
Старайся не использовать в функции больше 2-3 аргументов
Материал по этому вопросу:
https://github.com/ryanmcdermott/clean-code-javascript#function-arguments-2-or-fewer-ideally

2022-12-04 14:25 UTC, andrey-kudinov commented on src/ts/main.ts
> +import tabs from "./modules/tabs";
Я бы советовал в директории `modules` создать `index.js` и в нём собрать все импорты, чтобы из него экспортировать

Для **дефолтных** экспортов
```
// index.js
export { default } from './modals.ts'
export { default } from './tabs.ts'
```

Для **именных** импортов (мне больше нрав именные, они лучше поддерживаются редактором)
```
// index.js
export { modals } from './modals.ts'
export { tabs } from './tabs.ts'
```

Тогда в главном файле не будет большой портянки импортов
По мере роста проекта она бы увеличилась, лучше подумать об этом уже сейчас

```
// main.ts
import { modals, tabs } from "./modules
```

2022-12-05 18:46 UTC, andrey-kudinov commented on src/ts/main.ts
> +    headerSelector: '.glazing_slider',
Немножко форматирования не хватает

2022-12-06 13:53 UTC, dmitrykorochkin commented
Fix

2022-12-06 13:56 UTC, andrey-kudinov requested changes

2022-12-06 13:56 UTC, andrey-kudinov commented on src/ts/modules/tabs.ts
> +export const tabs = (arg: {
Ты можешь сразу деструктурировать прямо тут
Или ниже

2022-12-06 13:56 UTC, andrey-kudinov commented on src/ts/modules/tabs.ts
> +    const header: Element = document.querySelector(arg.headerSelector);
const { headerSelector, ..} = arg

2022-12-06 17:32 UTC, merged