Forms
dmitrykorochkin/Dev_project pull request #6
Opened 2022-12-08 17:36 UTC by dmitrykorochkin

Block form. Tested in openserver, phone mask added

2022-12-08 18:09 UTC, andrey-kudinov requested changes
Хорошая работа 👍
В коде имеются конфликты (merge conflicts)
Сделай пж `git pull origin main` чтобы подтянуть изменения и реши конфликты локально

2022-12-08 18:09 UTC, andrey-kudinov commented on src/ts/modules/forms.ts
> +    const message: MessageType = {
<img width="908" alt="image" src="https://user-images.githubusercontent.com/64890665/206529703-40c4f851-79f9-4f2b-824c-1a6580302e2c.png">


Не может найти переменную MessageType
Очевидно скорее всего у тебя был такой тип, возможно случайно удалил

2022-12-08 18:09 UTC, andrey-kudinov commented on src/ts/modules/forms.ts
> +    const clearInputs = (): void => {
Иногда такие вещи можно однострочниками делать
Но это просто псевдо эстетика

`const clearInputs = (): void => inputs.forEach(i => i = '')`

2022-12-08 18:09 UTC, andrey-kudinov commented on src/ts/modules/forms.ts
> +    const clearInputs = (): void => {
Не нужно исправлять, чисто для справки написал

2022-12-08 18:09 UTC, andrey-kudinov commented on src/ts/modules/forms.ts
> +            let statusMessage: Element = document.createElement('div');
`const`

2022-12-09 08:00 UTC, dmitrykorochkin commented on src/ts/modules/forms.ts
> +            let statusMessage: Element = document.createElement('div');
✅ Поправил

2022-12-09 08:00 UTC, dmitrykorochkin commented on src/ts/modules/forms.ts
> +    const message: MessageType = {
✅ Поправил

2022-12-09 08:01 UTC, merged