Modalstate
dmitrykorochkin/Dev_project pull request #7
Opened 2022-12-12 10:15 UTC by dmitrykorochkin

2022-12-12 10:22 UTC, andrey-kudinov requested changes
Хорошая работа 
Есть несколько комментариев, посмотри пж

2022-12-12 10:22 UTC, andrey-kudinov commented on src/ts/modules/changeModalState.ts
> +                            i === 0 ? state[prop] = 'Холодное' : state[prop] = 'Теплое';
Здесь лучше использовать следующую стилистику
a = condition ? b : c

2022-12-12 10:22 UTC, andrey-kudinov commented on src/ts/modules/changeModalState.ts
> +                                if(i == j) {
Здесь возможно лучше заменить в верстке на радио баттон и тогда тут не нужно будет отчекбоксывать
И по логике радио баттон больше подходит

2022-12-12 10:22 UTC, andrey-kudinov commented on src/ts/modules/changeModalState.ts
> +                        console.log('span');
Если console.log для дебага уже не нужен, его нужно удалить

2022-12-12 17:58 UTC, dmitrykorochkin commented on src/ts/modules/changeModalState.ts
> +                        console.log('span');
✅

2022-12-12 18:27 UTC, dmitrykorochkin commented on src/ts/modules/changeModalState.ts
> +                            i === 0 ? state[prop] = 'Холодное' : state[prop] = 'Теплое';
✅

2022-12-14 12:31 UTC, andrey-kudinov commented on src/index.html
> +                    <input class="checkbox-custom" type="radio" id="warm" name="contact" value="Теплое">
У тебя здесь у чекбокса один класс, а в функции ты обращаешься к нему по другому классу
Я думаю в этом проблема
Так же я уверен что здесь не нужно менять html, лучше оставить как было
Проблема в доступности (не работало переключение с клавиатуры) из-за стилей 
В частности из-за того что при создание кастомного чекбокса не совсем верно скрыли нативный чекбокс
Можем обсудить в тг

2022-12-15 06:06 UTC, andrey-kudinov commented on gulpfile.js
> +
Я думаю пробел случайно появился, убери пж

2022-12-15 06:07 UTC, andrey-kudinov commented on src/index.html
> +                     <input  class="checkbox" type="checkbox" name="checkbox-test">
type radio
value Холодное

2022-12-15 06:07 UTC, andrey-kudinov commented on src/index.html
> +                     <input  class="checkbox" type="checkbox" name="checkbox-test">
type radio
value Горячее

2022-12-15 16:49 UTC, merged