Timer
dmitrykorochkin/Dev_project pull request #8
Opened 2022-12-16 11:31 UTC by dmitrykorochkin

2022-12-16 13:01 UTC, andrey-kudinov requested changes

2022-12-16 13:01 UTC, andrey-kudinov commented on src/ts/modules/timer.ts
> +const timer = (id: number | string, deadline: string | number): void => {
Здесь вроде только string в обоих случаях 🤔

2022-12-16 13:01 UTC, andrey-kudinov commented on src/ts/main.ts
> +import timer from './modules/timer'
Тебе лучше складывать импорты в `index` так же как ты до этого делал с `modals` и `tabs`
Это хорошая практика
Так же с `changeModalState` и `timer` можно сделать

2022-12-17 06:14 UTC, dmitrykorochkin commented on src/ts/main.ts
> +    let deadline = '2022-12-31'
✅

2022-12-17 06:27 UTC, dmitrykorochkin commented on src/ts/modules/timer.ts
> +    const addZero = (num: number): number | string => {
✅

2022-12-17 06:44 UTC, dmitrykorochkin commented on src/ts/modules/timer.ts
> +    const getTimerRemaning = (endtime: any): any => {
Данный интерфейс создается для типизации объекта?  Ниже по комментариям для чего я должен его вызвать?
![image](https://user-images.githubusercontent.com/51984125/208229343-fca79510-b8ce-490a-b745-0ed4fed5b5d9.png)

2022-12-17 07:37 UTC, dmitrykorochkin commented on src/ts/main.ts
> +import timer from './modules/timer'
✅

2022-12-17 07:37 UTC, dmitrykorochkin commented on src/ts/modules/timer.ts
> +const timer = (id: number | string, deadline: string | number): void => {
✅

2022-12-17 07:37 UTC, dmitrykorochkin commented on src/ts/modules/timer.ts
> +            const time: any= getTimerRemaning(endtime);
✅

2022-12-17 07:37 UTC, dmitrykorochkin commented on src/ts/modules/timer.ts
> +    const setClock = (selector: any, endtime: any): void => {
✅

2022-12-17 07:37 UTC, dmitrykorochkin commented on src/ts/modules/timer.ts
> +    const getTimerRemaning = (endtime: any): any => {
✅

2022-12-17 07:38 UTC, dmitrykorochkin commented on src/ts/modules/timer.ts
> +    const getTimerRemaning = (endtime: any): any => {
✅

2022-12-17 07:38 UTC, dmitrykorochkin commented on src/ts/modules/timer.ts
> +    const addZero = (num: number): number | string => {
✅

2022-12-17 07:39 UTC, merged